apiVersion: apps/v1
kind: Deployment
metadata:
  name: nave-go
  labels:
    app: nave-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nave-go
  template:
    metadata:
      labels:
        app: nave-go
    spec:
      containers:
      - name: nave-go
        image: ghcr.io/pelegov/directeam:c6943e9
        ports:
        - containerPort: 8080